name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'
        channel: 'stable'
      - run: flutter --version
      
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --debug
      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk ./ExampleApp-SNAPSHOT.apk
      - name: Archive APK
        uses: actions/upload-artifact@v1
        with:
          name: android-build
          path: ./ExampleApp-SNAPSHOT.apk
